### ISSUE TITLE
modnames

### ISSUE THREAD

**Issue by wsor4035** [minetest-game-dev/minetest_game#1]
rename mods to mtg_modname. would do this all at once, but perhaps some mods such as default should be split first

**Comment by wsor4035** [comment]
this opens up the issue of dealing with dependency resolution, which will need to be investigated

**Comment by samarth-ramesh** [comment]
perhaps have empty mods that depend on the replacement. 
also, have one of these two (afaik)

1.  over ride registrations
2.  have a whole bunch of aliases
