### ISSUE TITLE
default master issue split

### ISSUE THREAD

**Issue by wsor4035** [minetest-game-dev/minetest_game#6]
master issue for discussing default spilt

my suggestion for spliting default up is as follows
mtg_core (containing sounds, etc, core things that other mods may depend on)
mtg_terrain (containing all the terrian nodes, possibly there block and brick forms?)
mtg_trees (containing trees)
other stuff being spilt out to mtg_modname

with default remaining and depending on the new mods, for mods that depend on it, and for aliases from new names to default:nodename

**Comment by samarth-ramesh** [comment]
hmm, looks good. but we may need to do testing with a lot of mods before we can make it official...  
but otherwise, go for it

**Comment by wsor4035** [comment]
I think that mtg_core needs to be done first, as it will involve how sounds are called, and will be easier to change that as part of moving to a new mod

**Comment by wsor4035** [comment]
sorry, my bad

**Comment by samarth-ramesh** [comment]
mhm, k... il finish me exam spend some time with her... heres to getting something done today

**Comment by BuckarooBanzay** [comment]
@wsor4035 Looks interesting, don't know how much time i'll have to contributing to this though :thinking: 
Also: it looks like you are using this on the `blockcity` server, is that correct?

**Comment by wsor4035** [comment]
@BuckarooBanzay no? not sure where you got that from. this project is completely separate from all my other stuff currently.
